/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupWorkflowsRouteImport } from './routes/setup.workflows'
import { Route as SetupUsersRolesRouteImport } from './routes/setup.users-roles'
import { Route as SetupSecurityRouteImport } from './routes/setup.security'
import { Route as SetupOrganizationStructureRouteImport } from './routes/setup.organization-structure'
import { Route as SetupModulesPermissionsRouteImport } from './routes/setup.modules-permissions'
import { Route as SetupAuditLogsRouteImport } from './routes/setup.audit-logs'
import { Route as SalesTargetVsAchievedRouteImport } from './routes/sales.target-vs-achieved'
import { Route as SalesLeadRouteImport } from './routes/sales.lead'
import { Route as SalesClientLossRouteImport } from './routes/sales.client-loss'
import { Route as OperationsFieldSenseRouteImport } from './routes/operations.field-sense'
import { Route as HrHrmsRouteImport } from './routes/hr.hrms'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceClientOnboardingRouteImport } from './routes/finance.client-onboarding'
import { Route as FinanceClientBillingRouteImport } from './routes/finance.client-billing'
import { Route as FinanceBudgetRouteImport } from './routes/finance.budget'
import { Route as SetupModuleSettingsSalesRouteImport } from './routes/setup.module-settings.sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWorkflowsRoute = SetupWorkflowsRouteImport.update({
  id: '/setup/workflows',
  path: '/setup/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupUsersRolesRoute = SetupUsersRolesRouteImport.update({
  id: '/setup/users-roles',
  path: '/setup/users-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSecurityRoute = SetupSecurityRouteImport.update({
  id: '/setup/security',
  path: '/setup/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupOrganizationStructureRoute =
  SetupOrganizationStructureRouteImport.update({
    id: '/setup/organization-structure',
    path: '/setup/organization-structure',
    getParentRoute: () => rootRouteImport,
  } as any)
const SetupModulesPermissionsRoute = SetupModulesPermissionsRouteImport.update({
  id: '/setup/modules-permissions',
  path: '/setup/modules-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAuditLogsRoute = SetupAuditLogsRouteImport.update({
  id: '/setup/audit-logs',
  path: '/setup/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTargetVsAchievedRoute = SalesTargetVsAchievedRouteImport.update({
  id: '/sales/target-vs-achieved',
  path: '/sales/target-vs-achieved',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLeadRoute = SalesLeadRouteImport.update({
  id: '/sales/lead',
  path: '/sales/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesClientLossRoute = SalesClientLossRouteImport.update({
  id: '/sales/client-loss',
  path: '/sales/client-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsFieldSenseRoute = OperationsFieldSenseRouteImport.update({
  id: '/operations/field-sense',
  path: '/operations/field-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const HrHrmsRoute = HrHrmsRouteImport.update({
  id: '/hr/hrms',
  path: '/hr/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceClientOnboardingRoute = FinanceClientOnboardingRouteImport.update({
  id: '/finance/client-onboarding',
  path: '/finance/client-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceClientBillingRoute = FinanceClientBillingRouteImport.update({
  id: '/finance/client-billing',
  path: '/finance/client-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetRoute = FinanceBudgetRouteImport.update({
  id: '/finance/budget',
  path: '/finance/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupModuleSettingsSalesRoute =
  SetupModuleSettingsSalesRouteImport.update({
    id: '/setup/module-settings/sales',
    path: '/setup/module-settings/sales',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance/budget': typeof FinanceBudgetRoute
  '/finance/client-billing': typeof FinanceClientBillingRoute
  '/finance/client-onboarding': typeof FinanceClientOnboardingRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/hr/hrms': typeof HrHrmsRoute
  '/operations/field-sense': typeof OperationsFieldSenseRoute
  '/sales/client-loss': typeof SalesClientLossRoute
  '/sales/lead': typeof SalesLeadRoute
  '/sales/target-vs-achieved': typeof SalesTargetVsAchievedRoute
  '/setup/audit-logs': typeof SetupAuditLogsRoute
  '/setup/modules-permissions': typeof SetupModulesPermissionsRoute
  '/setup/organization-structure': typeof SetupOrganizationStructureRoute
  '/setup/security': typeof SetupSecurityRoute
  '/setup/users-roles': typeof SetupUsersRolesRoute
  '/setup/workflows': typeof SetupWorkflowsRoute
  '/setup/module-settings/sales': typeof SetupModuleSettingsSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance/budget': typeof FinanceBudgetRoute
  '/finance/client-billing': typeof FinanceClientBillingRoute
  '/finance/client-onboarding': typeof FinanceClientOnboardingRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/hr/hrms': typeof HrHrmsRoute
  '/operations/field-sense': typeof OperationsFieldSenseRoute
  '/sales/client-loss': typeof SalesClientLossRoute
  '/sales/lead': typeof SalesLeadRoute
  '/sales/target-vs-achieved': typeof SalesTargetVsAchievedRoute
  '/setup/audit-logs': typeof SetupAuditLogsRoute
  '/setup/modules-permissions': typeof SetupModulesPermissionsRoute
  '/setup/organization-structure': typeof SetupOrganizationStructureRoute
  '/setup/security': typeof SetupSecurityRoute
  '/setup/users-roles': typeof SetupUsersRolesRoute
  '/setup/workflows': typeof SetupWorkflowsRoute
  '/setup/module-settings/sales': typeof SetupModuleSettingsSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance/budget': typeof FinanceBudgetRoute
  '/finance/client-billing': typeof FinanceClientBillingRoute
  '/finance/client-onboarding': typeof FinanceClientOnboardingRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/hr/hrms': typeof HrHrmsRoute
  '/operations/field-sense': typeof OperationsFieldSenseRoute
  '/sales/client-loss': typeof SalesClientLossRoute
  '/sales/lead': typeof SalesLeadRoute
  '/sales/target-vs-achieved': typeof SalesTargetVsAchievedRoute
  '/setup/audit-logs': typeof SetupAuditLogsRoute
  '/setup/modules-permissions': typeof SetupModulesPermissionsRoute
  '/setup/organization-structure': typeof SetupOrganizationStructureRoute
  '/setup/security': typeof SetupSecurityRoute
  '/setup/users-roles': typeof SetupUsersRolesRoute
  '/setup/workflows': typeof SetupWorkflowsRoute
  '/setup/module-settings/sales': typeof SetupModuleSettingsSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance/budget'
    | '/finance/client-billing'
    | '/finance/client-onboarding'
    | '/finance/expenses'
    | '/hr/hrms'
    | '/operations/field-sense'
    | '/sales/client-loss'
    | '/sales/lead'
    | '/sales/target-vs-achieved'
    | '/setup/audit-logs'
    | '/setup/modules-permissions'
    | '/setup/organization-structure'
    | '/setup/security'
    | '/setup/users-roles'
    | '/setup/workflows'
    | '/setup/module-settings/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance/budget'
    | '/finance/client-billing'
    | '/finance/client-onboarding'
    | '/finance/expenses'
    | '/hr/hrms'
    | '/operations/field-sense'
    | '/sales/client-loss'
    | '/sales/lead'
    | '/sales/target-vs-achieved'
    | '/setup/audit-logs'
    | '/setup/modules-permissions'
    | '/setup/organization-structure'
    | '/setup/security'
    | '/setup/users-roles'
    | '/setup/workflows'
    | '/setup/module-settings/sales'
  id:
    | '__root__'
    | '/'
    | '/finance/budget'
    | '/finance/client-billing'
    | '/finance/client-onboarding'
    | '/finance/expenses'
    | '/hr/hrms'
    | '/operations/field-sense'
    | '/sales/client-loss'
    | '/sales/lead'
    | '/sales/target-vs-achieved'
    | '/setup/audit-logs'
    | '/setup/modules-permissions'
    | '/setup/organization-structure'
    | '/setup/security'
    | '/setup/users-roles'
    | '/setup/workflows'
    | '/setup/module-settings/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceBudgetRoute: typeof FinanceBudgetRoute
  FinanceClientBillingRoute: typeof FinanceClientBillingRoute
  FinanceClientOnboardingRoute: typeof FinanceClientOnboardingRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  HrHrmsRoute: typeof HrHrmsRoute
  OperationsFieldSenseRoute: typeof OperationsFieldSenseRoute
  SalesClientLossRoute: typeof SalesClientLossRoute
  SalesLeadRoute: typeof SalesLeadRoute
  SalesTargetVsAchievedRoute: typeof SalesTargetVsAchievedRoute
  SetupAuditLogsRoute: typeof SetupAuditLogsRoute
  SetupModulesPermissionsRoute: typeof SetupModulesPermissionsRoute
  SetupOrganizationStructureRoute: typeof SetupOrganizationStructureRoute
  SetupSecurityRoute: typeof SetupSecurityRoute
  SetupUsersRolesRoute: typeof SetupUsersRolesRoute
  SetupWorkflowsRoute: typeof SetupWorkflowsRoute
  SetupModuleSettingsSalesRoute: typeof SetupModuleSettingsSalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/workflows': {
      id: '/setup/workflows'
      path: '/setup/workflows'
      fullPath: '/setup/workflows'
      preLoaderRoute: typeof SetupWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/users-roles': {
      id: '/setup/users-roles'
      path: '/setup/users-roles'
      fullPath: '/setup/users-roles'
      preLoaderRoute: typeof SetupUsersRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/security': {
      id: '/setup/security'
      path: '/setup/security'
      fullPath: '/setup/security'
      preLoaderRoute: typeof SetupSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/organization-structure': {
      id: '/setup/organization-structure'
      path: '/setup/organization-structure'
      fullPath: '/setup/organization-structure'
      preLoaderRoute: typeof SetupOrganizationStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/modules-permissions': {
      id: '/setup/modules-permissions'
      path: '/setup/modules-permissions'
      fullPath: '/setup/modules-permissions'
      preLoaderRoute: typeof SetupModulesPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/audit-logs': {
      id: '/setup/audit-logs'
      path: '/setup/audit-logs'
      fullPath: '/setup/audit-logs'
      preLoaderRoute: typeof SetupAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/target-vs-achieved': {
      id: '/sales/target-vs-achieved'
      path: '/sales/target-vs-achieved'
      fullPath: '/sales/target-vs-achieved'
      preLoaderRoute: typeof SalesTargetVsAchievedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/lead': {
      id: '/sales/lead'
      path: '/sales/lead'
      fullPath: '/sales/lead'
      preLoaderRoute: typeof SalesLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/client-loss': {
      id: '/sales/client-loss'
      path: '/sales/client-loss'
      fullPath: '/sales/client-loss'
      preLoaderRoute: typeof SalesClientLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/field-sense': {
      id: '/operations/field-sense'
      path: '/operations/field-sense'
      fullPath: '/operations/field-sense'
      preLoaderRoute: typeof OperationsFieldSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/hrms': {
      id: '/hr/hrms'
      path: '/hr/hrms'
      fullPath: '/hr/hrms'
      preLoaderRoute: typeof HrHrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/client-onboarding': {
      id: '/finance/client-onboarding'
      path: '/finance/client-onboarding'
      fullPath: '/finance/client-onboarding'
      preLoaderRoute: typeof FinanceClientOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/client-billing': {
      id: '/finance/client-billing'
      path: '/finance/client-billing'
      fullPath: '/finance/client-billing'
      preLoaderRoute: typeof FinanceClientBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budget': {
      id: '/finance/budget'
      path: '/finance/budget'
      fullPath: '/finance/budget'
      preLoaderRoute: typeof FinanceBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/module-settings/sales': {
      id: '/setup/module-settings/sales'
      path: '/setup/module-settings/sales'
      fullPath: '/setup/module-settings/sales'
      preLoaderRoute: typeof SetupModuleSettingsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceBudgetRoute: FinanceBudgetRoute,
  FinanceClientBillingRoute: FinanceClientBillingRoute,
  FinanceClientOnboardingRoute: FinanceClientOnboardingRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  HrHrmsRoute: HrHrmsRoute,
  OperationsFieldSenseRoute: OperationsFieldSenseRoute,
  SalesClientLossRoute: SalesClientLossRoute,
  SalesLeadRoute: SalesLeadRoute,
  SalesTargetVsAchievedRoute: SalesTargetVsAchievedRoute,
  SetupAuditLogsRoute: SetupAuditLogsRoute,
  SetupModulesPermissionsRoute: SetupModulesPermissionsRoute,
  SetupOrganizationStructureRoute: SetupOrganizationStructureRoute,
  SetupSecurityRoute: SetupSecurityRoute,
  SetupUsersRolesRoute: SetupUsersRolesRoute,
  SetupWorkflowsRoute: SetupWorkflowsRoute,
  SetupModuleSettingsSalesRoute: SetupModuleSettingsSalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
